# Generated by Django 4.2.1 on 2023-05-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='destinatio',
            new_name='destination',
        ),
    ]
